# Docker Compose BONITA project
version: '3.1'
services:
  restapi:
    build: ./src
    depends_on:
      - minio
      - mongo
    links:
      - mongo
      - minio

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 80:80

  redis:
    image: redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example